export const pictures = [
  { id: 1, src: "/reseda (1).jpeg", alt: "reseda (1)" },
  { id: 2, src: "/reseda (2).jpeg", alt: "reseda (2)" },
  { id: 3, src: "/reseda (3).jpeg", alt: "reseda (3)" },
  { id: 4, src: "/reseda (4).jpeg", alt: "reseda (4)" },
  { id: 5, src: "/reseda (5).jpeg", alt: "reseda (5)" },
  { id: 6, src: "/reseda (6).jpeg", alt: "reseda (6)" },
  { id: 7, src: "/reseda (7).jpeg", alt: "reseda (7)" },
  { id: 8, src: "/reseda (8).jpeg", alt: "reseda (8)" },
  { id: 9, src: "/reseda (9).jpeg", alt: "reseda (9)" },
  { id: 10, src: "/reseda (10).jpeg", alt: "reseda (10)" },
  { id: 11, src: "/reseda (11).jpeg", alt: "reseda (11)" },
  { id: 12, src: "/reseda (12).jpeg", alt: "reseda (12)" },
  { id: 13, src: "/reseda (13).jpeg", alt: "reseda (13)" },
  { id: 14, src: "/reseda (14).jpeg", alt: "reseda (14)" },
  { id: 15, src: "/reseda (15).jpeg", alt: "reseda (15)" },
  { id: 16, src: "/reseda (16).jpeg", alt: "reseda (16)" },
  { id: 17, src: "/reseda (17).jpeg", alt: "reseda (17)" },
  { id: 18, src: "/reseda (18).jpeg", alt: "reseda (18)" },
  { id: 19, src: "/reseda (19).jpg", alt: "reseda (19)" },
  { id: 20, src: null, alt: "" },
  { id: 21, src: null, alt: "" },
  { id: 22, src: null, alt: "" },
  { id: 23, src: null, alt: "" },
  { id: 24, src: null, alt: "" },
  { id: 25, src: null, alt: "" },
  { id: 26, src: null, alt: "" },
  { id: 27, src: null, alt: "" },
  { id: 28, src: null, alt: "" },
  { id: 29, src: null, alt: "" },
  { id: 30, src: null, alt: "" },
  { id: 31, src: null, alt: "" },
  { id: 32, src: null, alt: "" },
  { id: 33, src: null, alt: "" },
  { id: 34, src: null, alt: "" },
  { id: 35, src: null, alt: "" },
  { id: 36, src: null, alt: "" },
  { id: 37, src: null, alt: "" },
  { id: 38, src: null, alt: "" },
  { id: 39, src: null, alt: "" },
  { id: 40, src: null, alt: "" },
];
